### PR TITLE
Removed references to Actions.onErrorFrom.

### PR DESCRIPTION
**Pull request by akarnokd**

### CODE REVIEW

**Comment by ghost** [comment]
Hello--any chance this will be merged in?  It looks like the current version of RxJavaJoins (0.21.0) has runtime errors with the latest version of RxJava (1.0.2), unless I'm doing something wrong?  Works fine on 1.0.0-RC8 of RxJava.

> java.lang.NoSuchMethodError: rx.functions.Actions.onErrorFrom(Lrx/Observer;)Lrx/functions/Action1;
>     at rx.joins.Plan2.activate(Plan2.java:43)
>     at rx.joins.operators.OperatorJoinPatterns$1.call(OperatorJoinPatterns.java:114)
>     at rx.joins.operators.OperatorJoinPatterns$1.call(OperatorJoinPatterns.java:85)
